version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cv-management-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cv_management_system
    ports:
      - "5432:5432"
    volumes:
      - cv_management_postgres_data:/var/lib/postgresql/data

volumes:
  cv_management_postgres_data:
